import Navigation from '@component/components/Navigation'
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}





export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/flatly/bootstrap.min.css'/>
      </head>
      <body>
       <Navigation/>
        
      <div container p-4 >
      {children}
      </div>
        
        
        </body>


    </html>
  )
}
